package in.ac.kletech;

public abstract class CashCards {
	String sCardHolderName;
	String sBankName;
	double dShoppingAmount;
	double balance=0;
	
	CashCards(String sCardHolderName, String sBankName, double dShoppingAmount){
		this.sCardHolderName=sCardHolderName;
		this.sBankName=sBankName;
		this.dShoppingAmount=dShoppingAmount;
		
	}
	
	abstract void swipe();
}


class CreditCards extends CashCards{
	CreditCards(String sCardHolderName, String sBankName, double dShoppingAmount){
		super(sCardHolderName, sBankName, dShoppingAmount);
	
		
	}
	void swipe(){
		System.out.println("Swipe the Amount \nShopping Amount = Rs. "+dShoppingAmount);
	}
	
}

class DebitCards extends CashCards{
	DebitCards(String sCardHolderName, String sBankName, double dShoppingAmount){
		super(sCardHolderName, sBankName, dShoppingAmount);
		balance=5000d;
	}
	
	void swipe(){
		System.out.println("Pay the balance generated by credit card\nBalance = Rs. "+balance);
	}
	
	double generateBala(CreditCards c){
		if(balance>c.dShoppingAmount){
			return balance=balance-c.dShoppingAmount;
		}
		else
			return 0;
	}
}